P:
  START:
    - "8:40"
    - "10:10"
    - "12:15"
    - "13:45"
    - "15:15"
    - "16:45"
    - "18:00"
    - "19:20"
  END:
    - "9:55"
    - "11:25"
    - "13:30"
    - "15:00"
    - "16:30"
    - "18:00"
    - "19:15"
    - "20:35"
TERM:
  # 学年暦 ref 学群
  # http://www.tsukuba.ac.jp/campuslife/calendar/
  # https://www.tsukuba.ac.jp/admission/auditors/pdf/gun_3.pdf
  BEGIN:
    春:
      A: 2019/04/11
      B: 2019/05/24
      C: 2019/07/05
    夏: 2019/08/09
    秋:
      A: 2019/10/01
      B: 2019/11/12
      C: 2020/01/06
  # 13:00 となっているのは、GMTで指定するため (JSTなら、22:00)
  END:
    春:
      A: 2019/05/23 13:00
      B: 2019/06/27 13:00
      C: 2019/08/09 13:00
    夏: 2019/09/30 13:00
    秋:
      A: 2019/11/08 13:00
      B: 2019/12/19 13:00
      C: 2020/02/13 13:00
database:
  filename: "kamoku.db"
  table_name: "kamoku"
  column_names:
    - "code"
    - "name"
    - "method"
    - "unit"
    - "grade"
    - "term"
    - "period"
    - "location"
    - "teacher"
    - "abstruct"
    - "note"
    - "research_students"
    - "reason"
    - "english_name"
    - "time"
